[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Directory where the built files are located
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js version
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache favicon and manifest files
[[headers]]
  for = "/(favicon.ico|site.webmanifest|manifest.json|browserconfig.xml)"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Security headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Handle 404 page
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Handle sitemap
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  headers = {Content-Type = "application/xml"}

# Handle robots.txt
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  headers = {Content-Type = "text/plain"}
